services:
  cache:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6380:6379"
      
#  oidc.core-minimal:
#    image: oidc.core-minimal
#    build:
#      context: .
#      dockerfile: OIDC.Core-Minimal/Dockerfile
